### PR TITLE
String related fixes and support for passing request.json to Exceptional

### PR DESCRIPTION
**Pull request by jokull**

### CODE REVIEW

**Comment by jzempel** [comment]
Jökull,

Thanks for the pull request. I'm trying to wrap my brain around a couple of the details. Can you provide me an explanation (i.e. use case) for why you need to monkey patch the JSON encoder to ignore errors? Where are you seeing malformed UTF-8 data? Also, could you provide sample JSON request data that you want the extension to handle?

Cheers,
Jonathan.

**Comment by jokull** [comment]
I tried to extend the JSONEncoder class in a clean way but it's not broken down in any way I could see that allowed me to overwrite the `decode` methods in question. That's my I monkeypatch the string decode, to never fail.

What fails is a random bytestring. Try:

```
import os; os.urandom(20).decode('utf-8')
```

This is common to generate secret keys that are hard to guess. Flask documentation even suggests using os.urandom to create the SECRET_KEY used by the session module in Flask.

In any case, I think the error reporting should just "never fail". Decoding a string with "ignore" is a safe way to get at least something printable.

## 

The request.json stuff is kind of a controversial idea. I like to see what parameters were submitted against my JSON api however, and I believe other developers might have the same need. Tell me what you think : )

**Comment by jzempel** [comment]
So, to restate your underlying motive, you want Flask-Exceptional to support random byte strings without failing. (Like you, I generate keys as suggested by the [Flask documentation](http://flask.pocoo.org/docs/quickstart/#sessions), but I always hex-encode the result - so I wasn't seeing the issue you trying to guard against.) I'm going to make a bold assertion that the only Exceptional data that could potentially screw-up UTF-8 encoding would be coming from the `current_app.config` dictionary. If that's true (and I'm 90% convinced that it is), then a better fix would be localized to those particular values (near line 270):

```
if isinstance(value, basestring):
    value.decode("utf-8", "replace").encode("utf-8")
```

I'm extremely wary of monkey-patching json's `encode_basestring` and think that this approach is preferable. Either way, I'm interested to hear back from you re: my assertion and approach.

## 

I like the idea of reporting `request.json` data to Exceptional. But there will need to be some changes to support earlier versions of Flask along with keeping the current `request.form` processing intact. I'm looking at changing the initialization of `parameters = {}` in the `__get_request_data` method to something like this:

```
try:
    parameters = request.json or {}
except:
    parameters = {"INVALID_JSON": request.data}
```

Again, I'd like to hear your thoughts. Either way, I'm planning on incorporating your pull request changes into a modified version of exceptional.py which I will either commit or send to you for review.

Thanks again,
Jonathan.

**Comment by jokull** [comment]
So you think it's safe to assume all data sent to Exceptional is utf-8 decodable? I've seen some wacky HTTP User Agent strings, as an example of things that might trip the JSON payload sent to Exceptional. I feel strongly that this should simple never, ever fail. 

Looking forward to seeing your .json/.form idea.

**Comment by jzempel** [comment]
Ok, you talked me over the cliff. Please take a look at the [0.4.8 commit](https://github.com/jzempel/flask-exceptional/commit/7af6da87eebdd4809f2d7e6b399157f5c4ae8c6e) for a version of your changes - factored to support multiple versions of Flask, requiring simplejson >= 1.9.1 (for python 2.5), and with associated unit testing.

Have a look and let me know how it works for you. If everything looks fine, I'll close this pull request and deploy 0.4.8 to PyPI.

Thanks!

**Comment by jokull** [comment]
Great! Let me see if it behaves over the weekend. Will report here on monday.

**Comment by jokull** [comment]
All good from my end.

**Pull request closed without merging**
